site_name: Apache Kafka 容器化部署
# site_url: 'https://github.com/itboon/kafka-docker'

## Repository
repo_name: 'itboon/kafka-docker'
repo_url: 'https://github.com/itboon/kafka-docker'

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      # insert a blank space before the character
      permalink: " ¶"
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

theme:
  name: material
  font: false
  language: 'zh'
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.sections

  #palette:
  #  primary: "teal"
  #  accent: "green"

  include_sidebar: true

plugins:
  - search
  - minify:
      minify_html: true

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

# Page tree
nav:
  - Welcome: index.md
  - Docker:
    - Docker: docker.md
    - Docker Compose: compose.md
  - Helm: helm.md
  - '环境变量': env.md
