{{- if $.Values.controller.enabled -}}
{{- with $.Values.controller.service }}
{{- $component := "controller" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.controller.headless.serviceName" $ }}
  namespace: {{ include "kafka.namespace" $ }}
  labels:
    {{- include "kafka.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $component | quote }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ $.Values.controller.containerPort }}
      targetPort: controller
      protocol: TCP
      name: controller
  selector:
    {{- include "kafka.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $component | quote }}
{{- end }}
{{- end }}