apiVersion: v2
name: kafka
description: Helm chart for Apache Kafka.
type: application

version: 16.1.1
appVersion: v3.6.2

maintainers:
  - name: sir5kong
    url: "https://github.com/itboon/kafka-docker"

keywords:
  - kafka
  - streaming
  - kraft
