exporter:
  enabled: true
  image:
    repository: danielqsj/kafka-exporter
    # pullPolicy: IfNotPresent
    # tag: "latest"
  podAnnotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "9308"
    prometheus.io/scrape: "true"
  service:
    annotations: {}