image:
  repository: kafkace/kafka
  pullPolicy: IfNotPresent
  tag: v3.6.1

controller:
  replicaCount: 3
  heapOpts: "-Xms1024m -Xmx1024m"
  persistence:
    enabled: true
    size: 40Gi
    #storageClass: gp2
  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 200m
      memory: 2Gi

broker:
  replicaCount: 3
  heapOpts: "-Xms4096m -Xmx4096m"
  persistence:
    enabled: true
    size: 60Gi
    #storageClass: gp2
  resources:
    limits:
      cpu: 4
      memory: 16Gi
    requests:
      cpu: 500m
      memory: 6Gi