{{- $componet := include "kafka.broker.componet" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka.broker.fullname" . }}
  labels:
    {{- include "kafka.labels" $ | nindent 4 }}
    component: {{ $componet | quote }}
data:
  ## /etc/kafka/base/server.properties
  server.properties: |
{{- range $k, $v := .Values.broker.config }}
    {{ printf "%s=%s" $k $v }}
{{- end }}
{{- $replicaCount := .Values.broker.replicaCount | int }}
{{- if and $replicaCount (ge $replicaCount 3) }}
  {{- if not (hasKey .Values.broker.config "default.replication.factor" ) }}
    default.replication.factor=3
  {{- end }}
  {{- if not (hasKey .Values.broker.config "num.partitions" ) }}
    num.partitions=6
  {{- end }}
{{- end}}